language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  

before_install:
  pip install codecov
  pip install pytest


install: 
  "pip install -r requirements.txt"

script:
    - python setup.py install
    - pytest tests --api-key=${{ secrets.API_KEY }}
    - coverage run
    - bash <(curl -s https://codecov.io/bash)
  
